/**
 * Story + test label packs for the time, manage and pending-skeleton screens,
 * written for the invented «Salong Demo». Not shipped.
 */
import type { BookingSkeletonLabels } from '../booking-skeleton.js';
import type { ManageScreenLabels } from '../manage-screen.js';
import type { TimeScreenLabels } from '../time-screen.js';

const NBSP = '\u00A0';

export const timeLabelsNb: TimeScreenLabels = {
  'time.heading': 'Når vil du komme?',
  'time.dayStrip.legend': 'Velg dag',
  'time.nearest': 'nærmeste ledige',
  'time.current': '{time} · Din time nå',
  'time.nextFree': 'Første ledige time',
  'time.shortNotice': 'Ring oss hvis du vil komme i dag',
  'time.weekend.pct': `Helg: +{pct}${NBSP}% helgetillegg ({price})`,
  'time.weekend.mixed': 'Helg: inkludert helgetillegg ({price})',
  'time.month.show': 'Se hele måneden',
  'time.month.hide': 'Skjul måneden',
  'time.month.previous': 'Forrige måned',
  'time.month.next': 'Neste måned',
  'time.month.heading': '{month} {year}',
  'time.month.note': 'Du kan bestille inntil sju dager fram. Velg en dag for å se ledige tider.',
  'time.party.sequential': '{start} → {end}',
  'time.party.parallel': '{time} ({seats})',
  'time.party.seat': '{who} hos {stylist}',
  'time.party.seatSeparator': ' · ',
  'time.parallel.offer.two':
    'Ingen tider etter hverandre {day} – men dere kan komme samtidig kl. {time}.',
  'time.parallel.offer.other':
    'Ingen tider etter hverandre {day} – men alle kan komme samtidig kl. {time}.',
  'time.parallel.accept': 'Velg {time} samtidig',
  'time.empty.closed': 'Stengt {day} – prøv en annen dag.',
  'time.empty.over': 'Ikke flere tider {day} – prøv en annen dag.',
  'time.empty.full': 'Fullbooket {day} –',
  'time.empty.stylist': '{stylist} er fullbooket {day} –',
  'time.empty.unknown': 'Ingen ledige tider {day} –',
  'time.empty.callLink': 'ring oss på {phone}',
  'time.empty.callLinkAria': 'Ring oss på {phone}',
  'time.empty.callSuffix': ', så hjelper vi deg.',
  'time.empty.callPlain': 'ring oss, så hjelper vi deg.',
  'time.loading': 'Henter ledige tider …',
  'time.skeleton.dayPlaceholder': 'man. 00.',
  'time.taken.message': 'Den tiden ble akkurat tatt – her er de nærmeste',
  'time.taken.close': 'Lukk',
};

export const timeLabelsEn: TimeScreenLabels = {
  'time.heading': 'When would you like to come?',
  'time.dayStrip.legend': 'Choose a day',
  'time.nearest': 'nearest available',
  'time.current': '{time} · Your current time',
  'time.nextFree': 'First available time',
  'time.shortNotice': 'Call us if you want to come today',
  'time.weekend.pct': `Weekend: +{pct}${NBSP}% surcharge ({price})`,
  'time.weekend.mixed': 'Weekend: surcharge included ({price})',
  'time.month.show': 'See the whole month',
  'time.month.hide': 'Hide the month',
  'time.month.previous': 'Previous month',
  'time.month.next': 'Next month',
  'time.month.heading': '{month} {year}',
  'time.month.note': 'You can book up to seven days ahead. Choose a day to see free times.',
  'time.party.sequential': '{start} → {end}',
  'time.party.parallel': '{time} ({seats})',
  'time.party.seat': '{who} with {stylist}',
  'time.party.seatSeparator': ' · ',
  'time.parallel.offer.two':
    'No back-to-back times {day} – but you can both come at the same time at {time}.',
  'time.parallel.offer.other':
    'No back-to-back times {day} – but you can all come at the same time at {time}.',
  'time.parallel.accept': 'Take {time} together',
  'time.empty.closed': 'Closed {day} – try another day.',
  'time.empty.over': 'No more times {day} – try another day.',
  'time.empty.full': 'Fully booked {day} –',
  'time.empty.stylist': '{stylist} is fully booked {day} –',
  'time.empty.unknown': 'No free times {day} –',
  'time.empty.callLink': 'call us on {phone}',
  'time.empty.callLinkAria': 'Call us on {phone}',
  'time.empty.callSuffix': ' and we will help.',
  'time.empty.callPlain': 'call us and we will help.',
  'time.loading': 'Loading free times …',
  'time.skeleton.dayPlaceholder': 'Mon 00',
  'time.taken.message': 'That time was just taken – here are the nearest ones',
  'time.taken.close': 'Close',
};

export const manageLabelsNb: ManageScreenLabels = {
  ...timeLabelsNb,
  'manage.heading': 'Din time',
  'manage.serviceFallback': 'Time',
  'manage.card.named': '{name} – {service}',
  'manage.card.when': '{dateTime} · {price}',
  'manage.card.whenWithStylist': '{dateTime} hos {stylist} · {price}',
  'manage.appointment.named': '{name}s time',
  'manage.appointment.namedSibilant': "{name}' time",
  'manage.appointment.unnamed': 'timen',
  'manage.ringUs': 'ring oss',
  'manage.ringUsOn': 'ring oss på {phone}',
  'manage.callUs': 'Ring oss',
  'manage.callUsOn': 'Ring oss på {phone}',
  'manage.error.windowPassed': 'Det er for kort tid igjen til å endre selv – {ringUs}.',
  'manage.error.slotTaken': 'Den tiden ble akkurat tatt. Velg en annen.',
  'manage.error.notFound': 'Vi finner ikke denne timen. {callUs}, så hjelper vi deg.',
  'manage.error.conflict': 'Timen kan ikke endres nå – {ringUs}.',
  'manage.error.invalidInput': 'Den tiden kan ikke brukes. Velg en annen.',
  'manage.error.unavailable': 'Noe gikk galt. Prøv igjen, eller {ringUs}.',
  'manage.freeUntil': 'Gratis å endre fram til {dateTime}',
  'manage.remaining.in': 'om {amount}',
  'manage.remaining.daysAndHours': 'om {days} og {hours}',
  'manage.remaining.underMinute': 'om under ett minutt',
  'manage.remaining.day.one': '{count} dag',
  'manage.remaining.day.other': '{count} dager',
  'manage.remaining.hour.one': '{count} time',
  'manage.remaining.hour.other': '{count} timer',
  'manage.remaining.minute.one': '{count} minutt',
  'manage.remaining.minute.other': '{count} minutter',
  'manage.change': 'Endre tid',
  'manage.cancel': 'Avbestill',
  'manage.callToChange': 'Ring for å endre (under {hours} t igjen)',
  'manage.callToCancel': 'Ring for å avbestille (under {hours} t igjen)',
  'manage.blocked': 'Under {hours} timer igjen –',
  'manage.blocked.suffix': ', så finner vi ut av det.',
  'manage.blocked.plain': 'ring oss, så finner vi ut av det.',
  'manage.calendar': 'Legg i kalenderen',
  'manage.closed.cancelled': 'Denne timen er avbestilt.',
  'manage.closed.completed': 'Denne timen er fullført.',
  'manage.closed.noShow': 'Denne timen er avsluttet.',
  'manage.closed.pending': 'Denne timen er ikke bekreftet ennå.',
  'manage.closed.pendingCall': 'Ta kontakt på {phone}, så ordner vi det.',
  'manage.closed.pendingCallPlain': 'Ring oss, så hjelper vi deg.',
  'manage.bookNew': 'Bestill en ny time',
  'manage.party.heading': 'Flytte hele besøket, eller bare {who}?',
  'manage.party.justThisOne': 'Bare {who}',
  'manage.party.unnamed': 'denne timen',
  'manage.party.note': 'De andre beholder timene sine. Skal hele besøket flyttes,',
  'manage.party.noteSuffix': ', så flytter vi alle.',
  'manage.back': 'Tilbake',
  'manage.reschedule.lead': '{service} – velg ny tid',
  'manage.reschedule.leadWithStylist': '{service} hos {stylist} – velg ny tid',
  'manage.reschedule.failed': 'Vi får ikke hentet ledige tider nå –',
  'manage.reschedule.failedSuffix': ', så finner vi en tid.',
  'manage.reschedule.loading': 'Henter ledige tider …',
  'manage.move.question': 'Flytte {appointment} fra {from} til {to}?',
  'manage.move.questionWithStylist': 'Flytte {appointment} fra {from} til {to} hos {stylist}?',
  'manage.move.surcharge': `Merk: {weekday}spris {price} (+{pct}${NBSP}% helgetillegg)`,
  'manage.move.confirm': 'Bekreft ny tid',
  'manage.move.pickAnother': 'Velg en annen tid',
  'manage.cancel.question':
    'Avbestille {appointment} {dateTime}? Det er gratis fram til {hours} t før.',
  'manage.cancel.reasonLegend': 'Grunn (valgfritt)',
  'manage.cancel.reason.illness': 'Sykdom',
  'manage.cancel.reason.noLongerSuits': 'Passer ikke lenger',
  'manage.cancel.reason.other': 'Annet',
  'manage.cancel.confirm': 'Ja, avbestill',
  'manage.cancel.keep': 'Behold timen',
  'manage.cancelled': 'Timen er avbestilt. Vil du finne en ny tid med en gang?',
  'manage.cancelled.findNew': 'Finn en ny tid',
  'manage.moved': 'Timen er flyttet.',
  'manage.movedTo': 'Timen er flyttet til {dateTime}.',
  'manage.moved.view': 'Se timen',
  'manage.moved.noLink': 'Endringen er lagret.',
  'manage.moved.noLinkSuffix': 'hvis du vil endre den igjen.',
  'manage.portal': 'Se alle timene dine',
};

export const manageLabelsEn: ManageScreenLabels = {
  ...timeLabelsEn,
  'manage.heading': 'Your appointment',
  'manage.serviceFallback': 'Appointment',
  'manage.card.named': '{name} – {service}',
  'manage.card.when': '{dateTime} · {price}',
  'manage.card.whenWithStylist': '{dateTime} with {stylist} · {price}',
  'manage.appointment.named': "{name}'s appointment",
  'manage.appointment.namedSibilant': "{name}' appointment",
  'manage.appointment.unnamed': 'the appointment',
  'manage.ringUs': 'call us',
  'manage.ringUsOn': 'call us on {phone}',
  'manage.callUs': 'Call us',
  'manage.callUsOn': 'Call us on {phone}',
  'manage.error.windowPassed': 'It is too late to change this yourself – {ringUs}.',
  'manage.error.slotTaken': 'That time was just taken. Please choose another.',
  'manage.error.notFound': 'We cannot find this appointment. {callUs} and we will help.',
  'manage.error.conflict': 'The appointment cannot be changed right now – {ringUs}.',
  'manage.error.invalidInput': 'That time cannot be used. Please choose another.',
  'manage.error.unavailable': 'Something went wrong. Try again, or {ringUs}.',
  'manage.freeUntil': 'Free to change until {dateTime}',
  'manage.remaining.in': 'in {amount}',
  'manage.remaining.daysAndHours': 'in {days} and {hours}',
  'manage.remaining.underMinute': 'in under a minute',
  'manage.remaining.day.one': '{count} day',
  'manage.remaining.day.other': '{count} days',
  'manage.remaining.hour.one': '{count} hour',
  'manage.remaining.hour.other': '{count} hours',
  'manage.remaining.minute.one': '{count} minute',
  'manage.remaining.minute.other': '{count} minutes',
  'manage.change': 'Change time',
  'manage.cancel': 'Cancel',
  'manage.callToChange': 'Call to change (under {hours} h left)',
  'manage.callToCancel': 'Call to cancel (under {hours} h left)',
  'manage.blocked': 'Under {hours} hours left –',
  'manage.blocked.suffix': ' and we will sort it out.',
  'manage.blocked.plain': 'call us and we will sort it out.',
  'manage.calendar': 'Add to calendar',
  'manage.closed.cancelled': 'This appointment has been cancelled.',
  'manage.closed.completed': 'This appointment has been completed.',
  'manage.closed.noShow': 'This appointment is closed.',
  'manage.closed.pending': 'This appointment is not confirmed yet.',
  'manage.closed.pendingCall': 'Call us on {phone} and we will help.',
  'manage.closed.pendingCallPlain': 'Call us and we will help.',
  'manage.bookNew': 'Book a new appointment',
  'manage.party.heading': 'Move the whole visit, or just {who}?',
  'manage.party.justThisOne': 'Just {who}',
  'manage.party.unnamed': 'this appointment',
  'manage.party.note': 'Everyone else keeps their times. To move the whole visit,',
  'manage.party.noteSuffix': ' and we will move everyone.',
  'manage.back': 'Back',
  'manage.reschedule.lead': '{service} – choose a new time',
  'manage.reschedule.leadWithStylist': '{service} with {stylist} – choose a new time',
  'manage.reschedule.failed': 'We cannot load free times right now –',
  'manage.reschedule.failedSuffix': ' and we will find a time.',
  'manage.reschedule.loading': 'Loading free times …',
  'manage.move.question': 'Move {appointment} from {from} to {to}?',
  'manage.move.questionWithStylist': 'Move {appointment} from {from} to {to} with {stylist}?',
  'manage.move.surcharge': `Note: {weekday} price {price} (+{pct}${NBSP}% weekend surcharge)`,
  'manage.move.confirm': 'Confirm new time',
  'manage.move.pickAnother': 'Choose another time',
  'manage.cancel.question': 'Cancel {appointment} {dateTime}? It is free until {hours} h before.',
  'manage.cancel.reasonLegend': 'Reason (optional)',
  'manage.cancel.reason.illness': 'Illness',
  'manage.cancel.reason.noLongerSuits': 'No longer suits',
  'manage.cancel.reason.other': 'Other',
  'manage.cancel.confirm': 'Yes, cancel',
  'manage.cancel.keep': 'Keep the appointment',
  'manage.cancelled': 'The appointment is cancelled. Would you like to find a new time now?',
  'manage.cancelled.findNew': 'Find a new time',
  'manage.moved': 'The appointment has been moved.',
  'manage.movedTo': 'The appointment has been moved to {dateTime}.',
  'manage.moved.view': 'View the appointment',
  'manage.moved.noLink': 'The change is saved.',
  'manage.moved.noLinkSuffix': 'if you want to change it again.',
  'manage.portal': 'See all your appointments',
};

export const bookingSkeletonLabelsNb: BookingSkeletonLabels = {
  'bookingSkeleton.opening': 'Laster timebestilling …',
};

export const bookingSkeletonLabelsEn: BookingSkeletonLabels = {
  'bookingSkeleton.opening': 'Opening booking …',
};
