export type {
  MarketingBentoCardProps,
  MarketingBentoGridProps,
  MarketingCalloutProps,
  MarketingContactPerson,
  MarketingContactProps,
  MarketingCta,
  MarketingFAQItem,
  MarketingFAQProps,
  MarketingFooterColumn,
  MarketingFooterProps,
  MarketingHeaderProps,
  MarketingHeaderUser,
  MarketingLeadMagnetProps,
  MarketingNavItemDescriptor,
  MarketingOffice,
  MarketingShellProps,
  MarketingTrustBarProps,
  MarketingTrustStat,
} from './types.js';
