export type {
  MarketingAnnouncementBarProps,
  MarketingBentoCardProps,
  MarketingBentoGridProps,
  MarketingCalloutProps,
  MarketingContactPerson,
  MarketingContactProps,
  MarketingCTAProps,
  MarketingCta,
  MarketingFAQItem,
  MarketingFAQProps,
  MarketingFooterColumn,
  MarketingFooterProps,
  MarketingHeaderProps,
  MarketingHeaderUser,
  MarketingHeroProps,
  MarketingLeadMagnetProps,
  MarketingMegaMenuFeature,
  MarketingMegaMenuProps,
  MarketingNavItemDescriptor,
  MarketingNumberedFeature,
  MarketingNumberedFeaturesProps,
  MarketingOffice,
  MarketingShellProps,
  MarketingTrustBarProps,
  MarketingTrustStat,
} from './types.js';
