export type {
  ShellCommandDefinition,
  ShellContentLayout,
  ShellHostAdapter,
  ShellModuleDefinition,
  ShellNavItem,
  ShellPanelDefinition,
  ShellRailItem,
  ShellRenderContext,
  ShellRouteContext,
  ShellSearchParamsAdapter,
  ShellStateContextValue,
  ShellTab,
  ShellViewDefinition,
  ShellViewportBand,
} from './index.js';
export {
  buildShellSectionCommands,
  buildShellShortcutMap,
  getDefaultShellPanelView,
  getResolvedShellPanelWidth,
  getShellActionsFromMatches,
  getShellContentLayoutFromMatches,
  getShellContentMaxWidth,
  getShellPanelCollection,
  getShellPanelView,
  getShellPanelViewsFromMatches,
  getShellTabsFromMatches,
  isShellPanelViewAvailable,
  NavigationArea,
  resolveShellPanelView,
  ShellAppRail,
  ShellDesktopPanelDock,
  ShellFrame,
  ShellHeaderFrame,
  ShellModuleNav,
  ShellPanelRail,
  ShellPanelToggle,
  ShellScrollableContent,
  ShellStateProvider,
  ShellTabBar,
  useShellState,
  WorkbenchLayout,
} from './index.js';
