import { create } from 'storybook/theming';

const brand = {
  purple100: '#eeeaf5',
  purple500: '#7e3fac',
  purple600: '#6a2e96',
  neutral50: '#fafafa',
  neutral200: '#e4e4e7',
  neutral500: '#52525b',
  neutral800: '#18181b',
  neutral900: '#111113',
  neutral950: '#09090b',
};

export const medaLight = create({
  base: 'light',
  brandTitle: 'Meda',
  brandUrl: 'https://meda.medalsocial.com',
  brandTarget: '_self',
  colorPrimary: brand.purple600,
  colorSecondary: brand.purple500,
  appBg: brand.neutral50,
  appContentBg: '#ffffff',
  appBorderColor: brand.neutral200,
  appBorderRadius: 6,
  textColor: brand.neutral950,
  textInverseColor: brand.neutral50,
  textMutedColor: brand.neutral500,
  barTextColor: brand.neutral500,
  barSelectedColor: brand.purple600,
  barBg: '#ffffff',
  inputBg: '#ffffff',
  inputBorder: brand.neutral200,
  inputTextColor: brand.neutral950,
  inputBorderRadius: 6,
  fontBase: '"Geist", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  fontCode: '"Geist Mono", "SF Mono", "Fira Code", monospace',
});

export const medaDark = create({
  base: 'dark',
  brandTitle: 'Meda',
  brandUrl: 'https://meda.medalsocial.com',
  brandTarget: '_self',
  colorPrimary: brand.purple500,
  colorSecondary: brand.purple100,
  appBg: brand.neutral950,
  appContentBg: brand.neutral900,
  appBorderColor: '#2e2e33',
  appBorderRadius: 6,
  textColor: brand.neutral50,
  textInverseColor: brand.neutral950,
  textMutedColor: '#a1a1aa',
  barTextColor: '#a1a1aa',
  barSelectedColor: brand.purple100,
  barBg: brand.neutral900,
  inputBg: brand.neutral800,
  inputBorder: '#2e2e33',
  inputTextColor: brand.neutral50,
  inputBorderRadius: 6,
  fontBase: '"Geist", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  fontCode: '"Geist Mono", "SF Mono", "Fira Code", monospace',
});
